---
output: word_document
---


## Appendix CCC - ALL THE PLOTS ALL THE LAKES

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi=300)
```

```{r LoadSample}
# loading data to report sample sizes
load(file="Rdata/laketrout_sampling_formodel.Rdata")
library(magrittr)
library(jagshelper)

roundn <- paste0(formatC(round(nrow(laketrout), digits=-4), 
                         big.mark=",", format="f", digits=0), 
                 "+")
nw <- sum(!is.na(laketrout$Weight_g)) %>% 
  formatC(big.mark=",", format="f", digits=0)
nl <- sum(!is.na(laketrout$ForkLength_mm)) %>% 
  formatC(big.mark=",", format="f", digits=0)
na <- sum(!is.na(laketrout$Age)) %>% 
  formatC(big.mark=",", format="f", digits=0)

nlw <- sum(!is.na(laketrout$ForkLength_mm & laketrout$Weight_g)) %>% 
  formatC(big.mark=",", format="f", digits=0)
nla <- sum(!is.na(laketrout$ForkLength_mm & laketrout$Age)) %>% 
  formatC(big.mark=",", format="f", digits=0)

nllw <- length(unique(laketrout$LakeName[!is.na(laketrout$ForkLength_mm & laketrout$Weight_g)]))
nlla <- length(unique(laketrout$LakeName[!is.na(laketrout$ForkLength_mm & laketrout$Age)]))

nlakes <- length(unique(laketrout$LakeName))
```

```{r LoadModelResults}
## loading the JAGS output itself (this is a big file)
load(file="interim_posts/int_Winf_modelrun.Rdata")

# ^^^^^ update this file with non-interim model run ^^^^^

```



```{r, fig.width=8, fig.height=2.8, warning=FALSE}

par(mar=c(3, 3, 5, 0.3)+0.1)
par(mgp=c(2, 1, 0))
par(family="serif")
# par(cex.axis=1.2)
par(cex.lab=1.2)


## --- A COLLECTION OF SUMMARY PLOTS FOR EACH LAKE --- ##


# A good-enough sideways version of caterpillar (data is on x-axis)
side_cat <- function(x, a, xlab="", ylab="") { # a will be an index to highlight

  ci <- c(0.5, 0.95)

  loq <- apply(x, 2, quantile, p = (1 - ci)/2, na.rm = T)
  hiq <- apply(x, 2, quantile, p = 1 - (1 - ci)/2, na.rm = T)
  meds <- apply(x, 2, median, na.rm=T)

  plot(NA, xlim=range(0, loq, hiq, na.rm=TRUE), ylim=c(ncol(x),1),
       ylab=ylab, xlab=xlab, yaxt="n")

  segments(x0=loq[1,], x1=hiq[1,], y0=1:ncol(x),
           lend=1, lwd=3, col=adjustcolor(1, alpha.f=.2))
  segments(x0=loq[2,], x1=hiq[2,], y0=1:ncol(x),
           lend=1, lwd=1, col=adjustcolor(1, alpha.f=.2))

  segments(x0=loq[1,a], x1=hiq[1,a], y0=a,
           lend=1, lwd=6, col=1)
  segments(x0=loq[2,a], x1=hiq[2,a], y0=a,
           lend=1, lwd=2, col=1)
  segments(x0=meds[a], x1=meds[a], y0=a-1, y1=a+1,
           lend=1, lwd=2, col=1)

  # grid(nx=NULL, ny=NA)
}

# a quick function to add individual sideways caterpillar bars, given a single (MC)MC vector
catbars <- function(x, h, col=1) {
  ci <- c(0.5, 0.95)
  lolo <- quantile(x, p = (1 - ci)/2, na.rm = T)
  hihi <- quantile(x, p = 1 - (1 - ci)/2, na.rm = T)
  segments(x0=lolo[1], x1=hihi[1], y0=h, lwd=3, lend=1, col=col)
  segments(x0=lolo[2], x1=hihi[2], y0=h, lwd=1, lend=1, col=col)
}
```


```{r, fig.width=8, fig.height=2.8, warning=FALSE}

par(mar=c(3, 3, 5, 0.3)+0.1)
par(mgp=c(2, 1, 0))
par(family="serif")
# par(cex.axis=1.2)
par(cex.lab=1.2)
par(mfrow=c(1,3)) # was 4

## Actually plotting -- THIS WILL MAKE A LOT OF PLOTS, BE WARNED!

theselakes <- seq_along(lakenames)
# theselakes <- 4:6
for(i in theselakes) {
  par(xpd=FALSE)

  # L ~ Age
  plot(NA, xlab="Age", ylab="Length (mm)", main=lakenames[i],
       xlim=c(0, max(int_Winf_data$Age, na.rm=TRUE)),
       ylim=c(0, max(int_Winf_data$L[!is.na(int_Winf_data$Age)], na.rm=TRUE)))
  for(j in 1:ncol(int_Winf_jags_out$q50$Lfit)) {
    lines(int_Winf_jags_out$q50$Lfit[,j], col=adjustcolor(1, alpha.f = .3), lty=3)
  }
  if(i <= dim(int_Winf_jags_out$sims.list$Lfit)[3]) {
    envelope(int_Winf_jags_out$sims.list$Lfit[,,i], add=TRUE, col=adjustcolor(1, alpha.f=0.7))
  }
  points(x=int_Winf_data$Age[int_Winf_data$lake==i],
         y=int_Winf_data$L[int_Winf_data$lake==i])


  # W ~ Length
  plot(NA, xlab="Length (mm)", ylab="Weight (kg)", main="", #log="xy",lakenames[i]
       xlim=range(int_Winf_data$L[!is.na(int_Winf_data$logW)], na.rm=TRUE),
       ylim=range(exp(int_Winf_data$logW), na.rm=TRUE),
       # xlim=quantile(int_Winf_data$L[!is.na(int_Winf_data$logW)], na.rm=TRUE, p=c(.01,.999)),
       # ylim=quantile(exp(int_Winf_data$logW), na.rm=TRUE, p=c(.01,.999)),
       )
  for(j in 1:length(lakenames)) {
    curve(exp(int_Winf_jags_out$q50$b0_interp[j])*x^int_Winf_jags_out$q50$b1[j],
          add=TRUE, col=adjustcolor(1, alpha.f = .3), lty=3)
  }
  points(x=int_Winf_data$L[int_Winf_data$lake==i],
         y=exp(int_Winf_data$logW)[int_Winf_data$lake==i])
  lvec <- seq(from=min(int_Winf_data$L[!is.na(int_Winf_data$logW)], na.rm=TRUE),
              to=max(int_Winf_data$L[!is.na(int_Winf_data$logW)], na.rm=TRUE),
              length.out=20)
  envelope(exp(int_Winf_jags_out$sims.list$b0_interp[,i]) *
                t(outer(lvec, int_Winf_jags_out$sims.list$b1[,i], "^")),
              x=lvec, add=TRUE, col=adjustcolor(1, alpha.f=0.7))


  # # Linf by data sources
  # side_cat(x=int_Winf_jags_out$sims.list$Linf, a=i, xlab="Linf (mm)")
  # 
  # par(xpd=NA)
  # cols <- c(1, 2, 4) # ages, lengths, area
  # 
  # segments(x0=int_Winf_data$qL[i], y0=-5-1, y1=1+i, lty=2, col=cols[2])
  sig_L <- int_Winf_jags_out$sims.list$sig_L
  if(i <= dim(int_Winf_jags_out$sims.list$Lfit)[3]) {
    qLvec <- rnorm(n=nrow(sig_L), mean=int_Winf_data$qL[i], sd=sig_L[,i])
    # catbars(x=qLvec, h=-5, col=cols[2])
  }
  # 
  logmu_vec <- log(int_Winf_jags_out$sims.list$gam * (1 - exp(-int_Winf_jags_out$sims.list$lam * (1 + log(int_Winf_data$Area[i])))))
  sigLAvec <- int_Winf_jags_out$sims.list$sig_LA
  areaLvec <- rlnorm(n=length(logmu_vec), meanlog = logmu_vec, sdlog = sigLAvec)
  # # abline(v=median(areaLvec), lty=2)
  # segments(x0=median(areaLvec), y0=-3-1, y1=1+i, lty=2, col=cols[3])
  # catbars(x=areaLvec, h=-3, col=cols[3])
  # 
  # text(x=c(0, 0), y=c(-7, -5, -3)-1, pos=4, cex=0.5, col=cols,
  #      labels=paste(c("n ages =", "n lengths =", "area"),
  #                   c(laketrout_Winf$n_Age[i], laketrout_Winf$n_Length[i], "")))


  # Winf by data sources
  side_cat(x=int_Winf_jags_out$sims.list$Winf, a=i, xlab="Winf (kg)", ylab="All lakes")

  par(xpd=NA)
  # cols <- c(1, 2, 3, 4) # ages, lengths, area
  cols <- rep(adjustcolor(1,alpha.f=.8), 4) # ages, lengths, area
  
  barheights <- seq(to=-4, by=4.5, length.out=4)-1

  segments(x0=int_Winf_data$qW[i], y0=barheights[2], y1=1+i, lty=2, col=cols[2])
  sig_W <- int_Winf_jags_out$sims.list$sig_W
  if(i <= dim(int_Winf_jags_out$sims.list$Lfit)[3]) {
    qWvec <- rnorm(n=nrow(sig_W), mean=int_Winf_data$qW[i], sd=sig_W[,i])
    catbars(x=qWvec, h=barheights[2], col=cols[2])
  }

  qWLvec <- exp(int_Winf_jags_out$sims.list$b0_interp[,i])*qLvec^int_Winf_jags_out$sims.list$b1[,i]
  segments(x0=median(qWLvec), y0=barheights[3], y1=1+i, lty=2, col=cols[3])
  catbars(x=qWLvec, h=barheights[3], col=cols[3])

  areaWLvec <- exp(int_Winf_jags_out$sims.list$b0_interp[,i])*areaLvec^int_Winf_jags_out$sims.list$b1[,i]
  segments(x0=median(areaWLvec), y0=barheights[4], y1=1+i, lty=2, col=cols[4])
  catbars(x=areaWLvec, h=barheights[4], col=cols[4])

  text(x=-6, y=barheights, pos=4, cex=1, col=cols,
       labels=paste(c("n ages =", "n weights =", "n lengths =", "area"),
                    c(laketrout_Winf$n_Age[i], laketrout_Winf$n_Weight[i], laketrout_Winf$n_Length[i], "")))
}
```

comparable text
